# Generated by Django 4.0.3 on 2022-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=150)),
                ('image_a', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'BetterName',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_russian', models.CharField(max_length=150)),
                ('title_foreign', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_daily', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_of_exempler', models.IntegerField()),
                ('author', models.CharField(max_length=150)),
                ('date_registration', models.DateTimeField()),
                ('number_of_pages', models.IntegerField()),
                ('year_of_publication', models.DateField()),
                ('pubdate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'BetterName',
                'ordering': ['title_russian', '-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birthday', models.DateField()),
                ('ages', models.IntegerField()),
                ('number_of_passport', models.CharField(max_length=9)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Выберете жанр', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image_author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
