# Generated by Django 4.0.3 on 2022-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname']},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['title_russian', '-pubdate']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='image_a',
            new_name='image_author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='second_name',
            new_name='partonymic',
        ),
        migrations.AlterField(
            model_name='books',
            name='title_foreign',
            field=models.CharField(help_text='Введите название без кавычек', max_length=150),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_russian',
            field=models.CharField(help_text='Введите название без кавычек', max_length=150),
        ),
    ]
