# Generated by Django 4.0.3 on 2022-06-13 20:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_author_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8f14351b-3f64-45ee-b98b-3987a1814a03'), primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=10)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='ImageAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Image_author',
        ),
        migrations.DeleteModel(
            name='Image_book',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='amount_of_exempler',
            new_name='amount_ex',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='adress',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image_author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='partonymic',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customers',
            name='sex',
            field=models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman')], default='Male', max_length=7),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, help_text='Введите', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='main.author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(help_text='Введите', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(to='main.genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_foreign',
            field=models.CharField(blank=True, help_text='Введите', max_length=150),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_russian',
            field=models.CharField(help_text='Введите', max_length=150),
        ),
        migrations.AddField(
            model_name='imagebook',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.books'),
        ),
        migrations.AddField(
            model_name='imageauthor',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.books'),
        ),
    ]
