# Generated by Django 4.0.3 on 2022-06-14 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookinstance_imageauthor_imagebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b7348cf-0748-4376-b2d2-c4c81384613e'), primary_key=True, serialize=False),
        ),
    ]
