# Generated by Django 4.0.5 on 2022-06-14 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('989a42c8-8285-43af-b1a1-5d724714ef3b'), primary_key=True, serialize=False),
        ),
    ]
