# Generated by Django 4.0.3 on 2022-06-15 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['title_russian', '-pubdate'], 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36c1b643-466e-48ad-8be0-c8aa86b81829'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_foreign',
            field=models.CharField(blank=True, help_text='Введите', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
