# Generated by Django 4.0.5 on 2022-06-15 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_books_options_alter_author_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e145ce31-fa1b-412f-90c8-a8bae27d8772'), primary_key=True, serialize=False),
        ),
    ]
