# Generated by Django 4.0.5 on 2022-06-15 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68bd117a-5059-43a2-bd6d-44ba46c183ea'), primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='imageauthor',
            name='image',
        ),
        migrations.AddField(
            model_name='imageauthor',
            name='image',
            field=models.ManyToManyField(to='main.author'),
        ),
        migrations.RemoveField(
            model_name='imagebook',
            name='image',
        ),
        migrations.AddField(
            model_name='imagebook',
            name='image',
            field=models.ManyToManyField(to='main.books'),
        ),
    ]
