# Generated by Django 4.0.5 on 2022-06-15 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bookinstance_id_remove_imageauthor_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname'], 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'verbose_name_plural': 'Экземпляры книг'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='imageauthor',
            options={'verbose_name_plural': 'Изображения авторов'},
        ),
        migrations.AlterModelOptions(
            name='imagebook',
            options={'verbose_name_plural': 'Изображения книг'},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7571ab9-f2e7-499e-bad8-6583e29ba595'), primary_key=True, serialize=False),
        ),
    ]
