# Generated by Django 4.0.5 on 2022-06-15 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_author_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageauthor',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.imageauthor'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8679e6a-0c12-4b54-bd51-9764f7bf5b9f'), primary_key=True, serialize=False),
        ),
    ]
