# Generated by Django 4.0.5 on 2022-06-15 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_imageauthor_image_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79a0775c-4acf-4f13-8e9e-2a029057a0e9'), primary_key=True, serialize=False),
        ),
    ]
