# Generated by Django 4.0.5 on 2022-06-15 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageauthor',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('684b320f-b900-43c2-9f37-337fd219f6f0'), primary_key=True, serialize=False),
        ),
    ]
