# Generated by Django 4.0.5 on 2022-06-15 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_imageauthor_image_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ManyToManyField(to='main.imagebook'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ManyToManyField(to='main.imageauthor'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f58bbbb6-6139-4fde-af95-2fab1a569484'), primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='imagebook',
            name='image',
        ),
        migrations.AddField(
            model_name='imagebook',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
