# Generated by Django 4.0.5 on 2022-06-15 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_books_image_remove_author_image_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('092e64fc-f5f4-4c7e-9b87-e47e527ce749'), primary_key=True, serialize=False),
        ),
    ]
