# Generated by Django 4.0.5 on 2022-06-15 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0b1c806-349d-4fa9-a50b-19b7c1d8c914'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(help_text='Введите описание книги', max_length=1000),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_foreign',
            field=models.CharField(blank=True, help_text='Введите название на иностранном языке', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_russian',
            field=models.CharField(help_text='Введите название на русском зяыке', max_length=150),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='number_of_passport',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Введите', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='imageauthor',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
