# Generated by Django 4.0.5 on 2022-06-15 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_bookinstance_id_alter_books_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06e44445-6376-46db-a5e4-6b0a2c3ec3ac'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_russian',
            field=models.CharField(help_text='Введите название на русском языке', max_length=150),
        ),
    ]
